version: '3'
services: 
  web:
    image: nginx
    ports:
      - 80:80
    volumes: 
      - ./nginx/app.conf:/etc/nginx/nginx.conf
    depends_on: 
      - api
  api:
    build: .
    image: guilhermebehs/curso-docker
    depends_on: 
      - postgres

  postgres:
    image: postgres
    ports: 
      - "32768:5432" 
    env_file: 
      - ".env" 