version: '3'
services:
  
  banco:
    image: postgres
    volumes: 
      - /home/guilhermebehs/Documentos/postgres_folder_docker:/var/lib/postgresql/data 
    env_file: 
      - ".env"
  
  api_node:
    build: .
    image: guilhermebehs/curso-docker
    depends_on: 
      - banco
  
  web:
    image: nginx
    ports:
      - 80:80
    volumes: 
      - ./nginx/app.conf:/etc/nginx/nginx.conf
    depends_on: 
      - api_node
  